# Устанавливаем статус самого Log4j (WARN, чтобы не было лишнего шума)
status = warn

# Имя свойства для корневого логгера
rootLogger.level = debug
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = CONSOLE

# Консольный аппендер
appender.console.type = Console
appender.console.name = CONSOLE
appender.console.target = SYSTEM_OUT

# Формат вывода
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n
